// Code generated by terraform-plugin-framework-generator DO NOT EDIT.
package orgserviceaccount

import (
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-validators/setvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/conversion"
)

func ResourceSchema() schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"client_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The Client ID of the Service Account.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The date that the Service Account was created on. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"description": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Human readable description for the Service Account.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 250),
					stringvalidator.RegexMatches(regexp.MustCompile("^[\\p{L}\\p{N}\\-_.,' ]*$"), ""),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Human-readable name for the Service Account. The name is modifiable and does not have to be unique.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 64),
					stringvalidator.RegexMatches(regexp.MustCompile("^[\\p{L}\\p{N}\\-_.,' ]*$"), ""),
				},
			},
			"org_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [/orgs](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^([a-f0-9]{24})$"), ""),
				},
			},
			"roles": schema.SetAttribute{
				ElementType:         types.StringType,
				Required:            true,
				MarkdownDescription: "A list of organization-level roles for the Service Account.",
				Validators: []validator.Set{
					setvalidator.SizeAtLeast(1),
				},
			},
			"secret_expires_after_hours": schema.Int64Attribute{
				Required:            true,
				MarkdownDescription: "The expiration time of the new Service Account secret, provided in hours. The minimum and maximum allowed expiration times are subject to change and are controlled by the organization's settings.",
			},
			"secrets": schema.SetNestedAttribute{
				Computed:            true,
				MarkdownDescription: "A list of secrets associated with the specified Service Account.",
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.UseStateForUnknown(),
				},
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"created_at": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "The date that the secret was created on. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
						},
						"expires_at": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "The date for the expiration of the secret. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
						},
						"id": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Unique 24-hexadecimal digit string that identifies the secret.",
						},
						"last_used_at": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "The last time the secret was used. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
						},
						"masked_secret_value": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "The masked Service Account secret.",
						},
						"secret": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "The secret for the Service Account. It will be returned only the first time after creation.",
							Sensitive:           true,
						},
					},
				},
			},
		},
	}
}

func DataSourceSchema() dsschema.Schema {
	return conversion.DataSourceSchemaFromResource(ResourceSchema(), &conversion.DataSourceSchemaRequest{
		RequiredFields: []string{"client_id", "org_id"},
	})
}

type TFModel struct {
	Roles                   types.Set    `tfsdk:"roles"`
	ClientId                types.String `tfsdk:"client_id"`
	CreatedAt               types.String `tfsdk:"created_at"`
	Description             types.String `tfsdk:"description"`
	Name                    types.String `tfsdk:"name"`
	OrgId                   types.String `tfsdk:"org_id"`
	Secrets                 types.Set    `tfsdk:"secrets"`
	SecretExpiresAfterHours types.Int64  `tfsdk:"secret_expires_after_hours"`
}
type TFSecretsModel struct {
	CreatedAt         types.String `tfsdk:"created_at"`
	ExpiresAt         types.String `tfsdk:"expires_at"`
	Id                types.String `tfsdk:"id"`
	LastUsedAt        types.String `tfsdk:"last_used_at"`
	MaskedSecretValue types.String `tfsdk:"masked_secret_value"`
	Secret            types.String `tfsdk:"secret"`
}

var SecretObjectType = types.ObjectType{AttrTypes: map[string]attr.Type{
	"created_at":          types.StringType,
	"expires_at":          types.StringType,
	"id":                  types.StringType,
	"last_used_at":        types.StringType,
	"masked_secret_value": types.StringType,
	"secret":              types.StringType,
}}
